# users.http
@port = http://localhost:3000
# this is an id to use, using it as a variable does not seem to work correctly: 5c8a1d5b0190b214360dc057

# Get all users
GET {{port}}/users

###

# Get a specific user by ID
# Replace ':id' with an actual ID from your database
GET {{port}}/users/6559693de8d15f3dd14fc165

###

# Create a new user
# Modify the JSON body according to your schema
POST {{port}}/users
Content-Type: application/json

{
    "name": "user 10",
    "email": "user10@example.com",
    "role": "user",
    "active": true,
    "photo": "user-10.jpg",
    "password": "$2a$12$VPYaAAOsI44uhq11WbZ5R.cHT4.fGdlI9gKJd95jmYw3.sAsmbvBq"
  }

###

# Update an existing user
# Replace ':id' with an actual ID and modify the JSON body as needed
PATCH {{port}}/users/65598365f2f33257c0ed5c3e
Content-Type: application/json

{
    "name": "user 15",
    "email": "user15@example.com",
    "role": "user",
    "active": true,
    "photo": "user-15.jpg",
    "password": "$2a$12$Q0grHjH9PXc6SxivC8m12.2mZJ9BbKcgFpwSG4Y1ZEII8HJVzWeyS"
}

# {
#     "_id": "5c8a1d5b0190b214360dc057",
#     "name": "Jonas Schmedtmann",
#     "email": "admin@natours.io",
#     "role": "admin",
#     "active": true,
#     "photo": "user-1.jpg",
#     "password": "$2a$12$Q0grHjH9PXc6SxivC8m12.2mZJ9BbKcgFpwSG4Y1ZEII8HJVzWeyS"
# }
###

# Delete a contact
# Replace ':id' with the ID of the contact you want to delete
DELETE http://localhost:3000/users/65598365f2f33257c0ed5c3e

###