# users.http
@port = http://localhost:3000
# this is an id to use, using it as a variable does not seem to work correctly: 5c8a1d5b0190b214360dc057

# Get all users
GET {{port}}

###

# Get a specific user by ID
# Replace ':id' with an actual ID from your database
GET {{port}}/users/5c8a1dfa2f8fb814b56fa181

###

# Create a new user
# Modify the JSON body according to your schema
POST {{port}}/users
Content-Type: application/json

{
    "name": "John",
    "email": "Doe",
    "role": "johndoe@example.com",
    "active": "green",
    "photo": "05/10/2015",
    "password": "hi"
}

###

# Update an existing user
# Replace ':id' with an actual ID and modify the JSON body as needed
PUT {{port}}/users/5c8a1d5b0190b214360dc057
Content-Type: application/json

{
    "name": "user 10",
    "email": "user10@example.com",
    "role": "user",
    "active": true,
    "photo": "user-10.jpg",
    "password": "$2a$12$Q0grHjH9PXc6SxivC8m12.2mZJ9BbKcgFpwSG4Y1ZEII8HJVzWeyS"
}

# {
#     "_id": "5c8a1d5b0190b214360dc057",
#     "name": "Jonas Schmedtmann",
#     "email": "admin@natours.io",
#     "role": "admin",
#     "active": true,
#     "photo": "user-1.jpg",
#     "password": "$2a$12$Q0grHjH9PXc6SxivC8m12.2mZJ9BbKcgFpwSG4Y1ZEII8HJVzWeyS"
# }
###

# Delete a contact
# Replace ':id' with the ID of the contact you want to delete
DELETE http://localhost:3000/:id

###